api_key: sk-nsIxq2HnRLDlg7g8C699A6B6CbD045CdB1F0DcBd4811Bb37
api_type: request
api_url: https://www.apillm.online/v1/chat/completions
chat_template: null
dataset_args:
  ConvFinqa:
    dataset_id: D:\working_projects\compass\evalscope_fin\evalscope\benchmarks\ConvFinqa
    eval_split: test
    few_shot_num: 0
    few_shot_random: false
    metric_list:
    - AverageAccuracy
    name: ConvFinqa
    prompt_template: null
    query_template: null
    subset_list:
    - main
    system_prompt: ''
    train_split: null
  FinQA:
    dataset_id: D:\working_projects\compass\evalscope_fin\evalscope\benchmarks\FinQA
    eval_split: test
    few_shot_num: 0
    few_shot_random: false
    metric_list:
    - AverageAccuracy
    name: FinQA
    prompt_template: null
    query_template: null
    subset_list:
    - main
    system_prompt: ''
    train_split: null
  senti_data:
    dataset_id: D:\working_projects\compass\evalscope_fin\evalscope\benchmarks\senti_data
    eval_split: test
    few_shot_num: 0
    few_shot_random: false
    metric_list:
    - AverageAccuracy
    name: senti_data
    prompt_template: null
    query_template: null
    subset_list:
    - main
    system_prompt: ''
    train_split: null
dataset_dir: C:\Users\OMEN\.cache\modelscope\hub\datasets
dataset_hub: modelscope
datasets:
- senti_data
- FinQA
- ConvFinqa
debug: false
dry_run: false
eval_backend: Native
eval_batch_size: 20
eval_config: null
eval_type: service
generation_config:
  max_tokens: 4096
  n: 1
  temperature: 0.6
  top_p: 0.95
headers: null
limit: 1000
mem_cache: false
model: qwen2.5-32b-instruct
model_args:
  precision: torch.float16
  revision: master
model_id: qwen2.5-32b-instruct
outputs: null
seed: 42
stage: all
stream: true
template_type: null
timeout: 60
use_cache: null
work_dir: ./outputs\20250306_185503
